// Dados de exemplo (fictícios) da tela Amazon. Antes ficavam dentro de pages-render.test.tsx.
import {
  resumoAmazon,
  asin360,
  termosAds,
  shareDeBusca,
  reposicaoFba,
  recompraAsin,
  organicoVsAds,
  vendasPorHora,
  alvosKeywords,
  alvosSd,
  classificaLances,
  adsUnificados,
} from "@/lib/amazon";
import {
  tendenciaSemanal,
  hojeAteAgora,
  buyBoxCompleto,
  qualidadeAnuncio,
  estoqueFba,
  sbParaTermos,
  sdPorProduto,
  campanhasNoLimite,
  pedidosAmazon,
} from "@/lib/amazon-operacao";
import { amazonPainelFixture } from "./painel-ads-fixture";

// Segunda leva: tendência, hoje, Buy Box completo, anúncio, estoque FBA, SB/SD, orçamento e pedidos.
export const AMZ_HOJE = "2026-10-06";
const segundas = Array.from({ length: 12 }, (_, i) =>
  new Date(Date.parse("2026-07-13T00:00:00Z") + i * 7 * 86400000).toISOString().slice(0, 10),
);
export const amz2 = {
  semanas: segundas.map((d, i) => ({
    semana: `S${i + 1}`,
    semana_ini: d,
    faturamento: 18000 + i * 900 - (i === 11 ? 12000 : 0),
    pedidos: 180 + i * 8 - (i === 11 ? 120 : 0),
    unidades: 200 + i * 9,
    invest_ads: 2500 + i * 80,
    tacos_pct: 0.12,
    roas_ads: 4.1,
    roas_total: 7.5,
    conversao_pct: 0.11,
    devolucao_pct: 0.02,
    parcial: i === 11,
    ads_maturando: i >= 10,
  })),
  intraday: [
    { data: AMZ_HOJE, faixa: "00h–06h", venda_total: 400, pedidos: 4, unidades: 5 },
    { data: AMZ_HOJE, faixa: "06h–12h", venda_total: 1300, pedidos: 12, unidades: 14 },
    { data: "2026-09-29", faixa: "00h–06h", venda_total: 300, pedidos: 3, unidades: 3 },
    { data: "2026-09-29", faixa: "06h–12h", venda_total: 1100, pedidos: 10, unidades: 11 },
    { data: "2026-09-29", faixa: "12h–18h", venda_total: 1500, pedidos: 14, unidades: 15 },
  ],
  buybox: [
    {
      asin: "B0CREA",
      ganho_buybox: true,
      meu_preco: 89.9,
      buybox_preco: 89.9,
      menor_preco_concorrente: 94.9,
      n_ofertas: 6,
      n_concorrentes: 5,
      buybox_fba: true,
    },
    {
      asin: "B0WHEY",
      ganho_buybox: false,
      concorrente_no_bb: true,
      meu_preco: 199.9,
      buybox_preco: 189.9,
      menor_preco_concorrente: 189.9,
      n_ofertas: 4,
      n_concorrentes: 3,
      buybox_fba: true,
    },
    {
      asin: "B0PRE",
      ganho_buybox: false,
      meu_preco: 99,
      buybox_preco: 99.9,
      menor_preco_concorrente: 99.9,
      n_ofertas: 2,
      n_concorrentes: 1,
      buybox_fba: false,
    },
  ],
  cadastro: [
    {
      asin: "B0CREA",
      titulo: "Creatina Amazon 300g",
      n_fotos: 8,
      n_bullets: 5,
      tem_aplus: true,
      tem_descricao: true,
      tem_ingredientes: true,
      comprimento_titulo: 120,
      faltas: [],
      bsr: 350,
      bsr_categoria: "Saúde e Cuidados Pessoais",
    },
    {
      asin: "B0WHEY",
      titulo: "Whey Amazon 900g",
      n_fotos: 4,
      n_bullets: 3,
      tem_aplus: true,
      tem_descricao: false,
      tem_ingredientes: false,
      comprimento_titulo: 60,
      faltas: ["peso"],
      bsr: 2100,
      bsr_categoria: "Saúde e Cuidados Pessoais",
    },
  ],
  estoque: [
    {
      asin: "B0CREA",
      seller_sku: "CREA300",
      product_name: "Creatina Amazon 300g",
      fulfillable: 90,
      reservado_total: 12,
      reservado_pedido: 8,
      reservado_transito: 4,
      reservado_fc: 0,
      inbound_receiving: 50,
      imprestavel_total: 3,
      imprestavel_vencido: 2,
      imprestavel_danificado_cliente: 1,
    },
    {
      asin: "B0WHEY",
      seller_sku: "WHEY900",
      product_name: "Whey Amazon 900g",
      fulfillable: 0,
      reservado_total: 5,
      reservado_pedido: 5,
      inbound_shipped: 200,
    },
  ],
  reposicao: [
    { sku: "CREA300", asin: "B0CREA", titulo: "Creatina Amazon 300g", cobertura_dias: 8 },
    { sku: "WHEY900", asin: "B0WHEY", titulo: "Whey Amazon 900g", cobertura_dias: 0 },
  ],
  sbTermos: [
    {
      data: "2026-09-03",
      campaign_name: "SB Marca",
      search_term: "creatina soldiers",
      keyword: "soldiers",
      match_type: "BROAD",
      cost: 60,
      clicks: 30,
      purchases: 5,
      sales: 600,
    },
    {
      data: "2026-09-03",
      campaign_name: "SB Marca",
      search_term: "suplemento barato",
      keyword: "suplemento",
      match_type: "BROAD",
      cost: 45,
      clicks: 20,
      purchases: 0,
      sales: 0,
    },
  ],
  sdProduto: [
    {
      data: "2026-09-03",
      asin: "B0CREA",
      sku: "CREA300",
      cost: 200,
      clicks: 150,
      purchases: 9,
      sales: 900,
    },
  ],
  adsCampanhas: [
    ...Array.from({ length: 10 }, (_, i) => ({
      data: `2026-09-${String(i + 1).padStart(2, "0")}`,
      campaign_id: "c1",
      cost: 98,
      sales_14d: 500,
    })),
    ...Array.from({ length: 10 }, (_, i) => ({
      data: `2026-09-${String(i + 1).padStart(2, "0")}`,
      campaign_id: "c2",
      cost: 40,
      sales_14d: 100,
    })),
  ],
  campanhas: [
    {
      campaign_id: "c1",
      campaign_name: "SP Creatina",
      ad_type: "SP",
      budget: 100,
      status: "ENABLED",
    },
    { campaign_id: "c2", campaign_name: "SP Whey", ad_type: "SP", budget: 100, status: "ENABLED" },
  ],
  pedidos: [
    {
      amazon_order_id: "701-1",
      purchase_dia: "2026-09-02",
      order_status: "Shipped",
      fulfillment_channel: "AFN",
      sku: "CREA300",
      quantity: 2,
      item_price: 179.8,
    },
    {
      amazon_order_id: "701-2",
      purchase_dia: "2026-09-03",
      order_status: "Shipped",
      fulfillment_channel: "AFN",
      sku: "CREA300",
      quantity: 1,
      item_price: 89.9,
    },
    {
      amazon_order_id: "701-3",
      purchase_dia: "2026-09-04",
      order_status: "Shipped",
      fulfillment_channel: "AFN",
      sku: "WHEY900",
      quantity: 1,
      item_price: 199.9,
    },
    {
      amazon_order_id: "701-4",
      purchase_dia: "2026-09-05",
      order_status: "Pending",
      fulfillment_channel: "AFN",
      sku: "CREA300",
      quantity: 1,
      item_price: 89.9,
    },
    {
      amazon_order_id: "702-1",
      purchase_dia: "2026-09-06",
      order_status: "Shipped",
      fulfillment_channel: "MFN",
      sku: "WHEY900",
      quantity: 1,
      item_price: 199.9,
    },
    {
      amazon_order_id: "702-2",
      purchase_dia: "2026-09-07",
      order_status: "Canceled",
      fulfillment_channel: "MFN",
      sku: "WHEY900",
      quantity: 1,
      item_price: 199.9,
    },
  ],
};
const amzVendas = new Map([
  ["B0CREA", 12000],
  ["B0WHEY", 8000],
]);
const amzTitulos = new Map([
  ["B0CREA", "Creatina Amazon 300g"],
  ["B0WHEY", "Whey Amazon 900g"],
  ["CREA300", "Creatina Amazon 300g"],
  ["WHEY900", "Whey Amazon 900g"],
]);

const AMZ_DE = "2026-09-01";
const AMZ_ATE = "2026-09-30";
export const amazonFixture = {
  resumo: resumoAmazon(
    [
      {
        data: "2026-09-02",
        vendas: 20000,
        unidades: 200,
        sessoes: 4000,
        buybox_pct: 0.86,
        unidades_devolvidas: 4,
      },
    ],
    adsUnificados(
      [
        {
          data: "2026-09-02",
          ad_type: "SP",
          cost: 1500,
          sales_14d: 7500,
          sales_7d: 6000,
          clicks: 900,
        },
      ],
      [{ data: "2026-09-02", campaign_id: "sb1", cost: 600, sales: 2400, clicks: 200 }],
      [{ data: "2026-09-03", campaign_id: "sd1", cost: 300, sales: 900, clicks: 150 }],
    ),
    AMZ_DE,
    AMZ_ATE,
    "2026-10-06",
  ),
  asins: asin360(
    [
      {
        data: "2026-09-02",
        child_asin: "B0CREA",
        vendas: 12000,
        unidades: 120,
        sessoes: 1500,
        buybox_pct: 1,
      },
      {
        data: "2026-09-02",
        child_asin: "B0WHEY",
        vendas: 8000,
        unidades: 80,
        sessoes: 2500,
        buybox_pct: 0.7,
      },
    ],
    [
      {
        asin: "B0WHEY",
        ganho_buybox: false,
        concorrente_no_bb: true,
        meu_preco: 199.9,
        menor_preco_concorrente: 189.9,
      },
    ],
    [{ asin: "B0CREA", seller_sku: "CREA300", fulfillable: 90 }],
    [
      {
        asin: "B0CREA",
        sku: "CREA300",
        em_fba: true,
        cobertura_dias: 8,
        titulo: "Creatina Amazon 300g",
        fba_disponivel: 90,
      },
    ],
    [{ asin: "B0WHEY", titulo: "Whey Amazon 900g", tem_aplus: true }],
    AMZ_DE,
    AMZ_ATE,
  ),
  termos: termosAds(
    [
      {
        data: "2026-09-02",
        campaign_name: "C",
        search_term: "pre treino barato",
        keyword_text: "pre treino",
        match_type: "BROAD",
        cost: 80,
        clicks: 40,
        purchases_14d: 0,
        sales_14d: 0,
      },
      {
        data: "2026-09-02",
        campaign_name: "C",
        search_term: "creatina monohidratada",
        keyword_text: "creatina",
        match_type: "BROAD",
        cost: 50,
        clicks: 30,
        purchases_14d: 6,
        sales_14d: 900,
      },
      {
        data: "2026-09-02",
        campaign_name: "C",
        search_term: "whey",
        keyword_text: "whey",
        match_type: "BROAD",
        cost: 300,
        clicks: 100,
        purchases_14d: 3,
        sales_14d: 400,
      },
    ],
    AMZ_DE,
    AMZ_ATE,
  ),
  share: shareDeBusca([
    {
      semana_fim: "2026-09-20",
      termo: "creatina",
      nosso: true,
      click_share: 0.2,
      conversion_share: 0.25,
      rank_busca: 4,
    },
    {
      semana_fim: "2026-09-27",
      termo: "creatina",
      nosso: true,
      click_share: 0.12,
      conversion_share: 0.15,
      rank_busca: 4,
    },
  ]),
  reposicao: reposicaoFba(
    [
      {
        sku: "CREA300",
        asin: "B0CREA",
        titulo: "Creatina Amazon 300g",
        em_fba: true,
        fba_disponivel: 90,
        cobertura_dias: 8,
        enviar_30d: 300,
        alerta: "repor",
      },
    ],
    [{ seller_sku: "CREA300", imprestavel_total: 3 }],
  ),
  recompra: recompraAsin([
    {
      asin: "B0CREA",
      mes_fim: "2026-09-30",
      clientes_unicos: 300,
      pct_clientes_repetem: 0.18,
      receita_recompra: 4000,
    },
  ]),
  organico: organicoVsAds(
    [
      { semana_fim: "2026-09-20", termo: "whey", nosso: true, click_share: 0.2, rank_busca: 1 },
      { semana_fim: "2026-09-27", termo: "whey", nosso: true, click_share: 0.05, rank_busca: 1 },
      {
        semana_fim: "2026-09-27",
        termo: "creatina pura",
        nosso: true,
        click_share: 0.5,
        rank_busca: 3,
      },
    ],
    [{ data: "2026-09-02", search_term: "creatina pura", cost: 400, sales_14d: 2000 }],
    AMZ_DE,
    AMZ_ATE,
  ),
  horas: vendasPorHora(
    [
      { data: "2026-09-06", hora: 21, venda: 900, pedidos: 9 },
      { data: "2026-09-07", hora: 9, venda: 100, pedidos: 1 },
    ],
    AMZ_DE,
    AMZ_ATE,
  ),
  lances: {
    keywords: classificaLances(
      alvosKeywords(
        [
          {
            data: "2026-09-02",
            campaign_name: "SP Creatina",
            keyword: "creatina 1kg",
            match_type: "EXACT",
            cost: 100,
            clicks: 100,
            purchases_14d: 10,
            sales_14d: 1000,
          },
          {
            data: "2026-09-02",
            campaign_name: "SP Whey",
            keyword: "whey protein",
            match_type: "BROAD",
            cost: 300,
            clicks: 150,
            purchases_14d: 2,
            sales_14d: 600,
          },
        ],
        AMZ_DE,
        AMZ_ATE,
      ),
    ),
    sd: classificaLances(alvosSd([], AMZ_DE, AMZ_ATE)),
  },
  termosSb: termosAds(sbParaTermos(amz2.sbTermos), AMZ_DE, AMZ_ATE),
  sdProduto: sdPorProduto(amz2.sdProduto, AMZ_DE, AMZ_ATE, amzTitulos),
  orcamento: campanhasNoLimite(amz2.adsCampanhas, amz2.campanhas, AMZ_DE, AMZ_ATE),
  estoqueFba: estoqueFba(amz2.estoque, amz2.reposicao),
  buybox: buyBoxCompleto(amz2.buybox, amzVendas, amzTitulos),
  qualidade: qualidadeAnuncio(amz2.cadastro, amzVendas),
  tendencia: tendenciaSemanal(amz2.semanas),
  hoje: hojeAteAgora(amz2.intraday, AMZ_HOJE),
  pedidos: pedidosAmazon(amz2.pedidos, AMZ_DE, AMZ_ATE, amzTitulos),
  painel: amazonPainelFixture,
  erros: { brand: "timeout" },
};
