// Dados de exemplo do CRM 2.0 (sem dados pessoais: só chaves fictícias). Usado nos testes e na prévia.
import {
  filaDeAcao,
  calibracao,
  reguaReposicao,
  emailRD,
  automacoesRD,
  utmEmail,
  funilLeads,
  acoesGrowth,
  saudeKlaviyo,
  alertasCRM,
} from "@/lib/crm";

export const DE = "2026-09-01";
export const ATE = "2026-09-30";
export const AGORA = "2026-09-30T12:00:00Z";

export const raw = {
  perfis: [
    {
      cliente_chave: "c_9f2a71b0e4d3",
      acao: "recompra",
      acionavel: true,
      chance_30: 62,
      chance_90: 81,
      valor_esperado_90: 410,
      dias_ultima_compra: 41,
      dias_atraso: 6,
      ritmo_dias: 35,
      produto_provavel: "Creatina 300g",
      sku_provavel: "CREA300",
      pedidos: 5,
      ticket_medio: 160,
      canal_ultimo: "site",
    },
    {
      cliente_chave: "c_1b7e55c09a12",
      acao: "valioso_em_risco",
      acionavel: true,
      chance_30: 18,
      chance_90: 44,
      valor_esperado_90: 380,
      dias_ultima_compra: 120,
      dias_atraso: 60,
      ritmo_dias: 60,
      produto_provavel: "Whey 900g",
      sku_provavel: "WHEY900",
      pedidos: 8,
      ticket_medio: 240,
      canal_ultimo: "mercado_livre",
    },
    {
      cliente_chave: "c_44d0a8f3b2c6",
      acao: "segunda_compra",
      acionavel: true,
      chance_30: 22,
      chance_90: 39,
      valor_esperado_90: 95,
      dias_ultima_compra: 28,
      dias_atraso: null,
      ritmo_dias: null,
      produto_provavel: "Creatina 300g",
      sku_provavel: "CREA300",
      pedidos: 1,
      ticket_medio: 120,
      canal_ultimo: "tiktok_shop",
    },
    {
      cliente_chave: "c_0000aguarda",
      acao: "aguardar",
      acionavel: false,
      chance_30: 5,
      chance_90: 30,
      valor_esperado_90: 999,
      pedidos: 2,
    },
  ],
  acuracia: [
    {
      horizonte_dias: 30,
      faixa: "0-20%",
      clientes: 4200,
      previsto_pct: 9,
      realizado_pct: 8,
      gerado_em: "2026-09-30",
    },
    {
      horizonte_dias: 30,
      faixa: "20-50%",
      clientes: 1300,
      previsto_pct: 34,
      realizado_pct: 27,
      gerado_em: "2026-09-30",
    },
    {
      horizonte_dias: 30,
      faixa: "50-100%",
      clientes: 380,
      previsto_pct: 66,
      realizado_pct: 51,
      gerado_em: "2026-09-30",
    },
    {
      horizonte_dias: 90,
      faixa: "0-20%",
      clientes: 4000,
      previsto_pct: 14,
      realizado_pct: 21,
      gerado_em: "2026-09-30",
    },
  ],
  ciclos: [
    {
      sku: "CREA300",
      produto: "Creatina 300g",
      clientes: 2400,
      compras: 5100,
      recompras: 2700,
      ciclo_mediano: 38,
      pct_retorno_30: 12,
      pct_retorno_60: 26,
      pct_retorno_90: 34,
    },
    {
      sku: "WHEY900",
      produto: "Whey 900g",
      clientes: 1800,
      compras: 3000,
      recompras: 1200,
      ciclo_mediano: 45,
      pct_retorno_30: 8,
      pct_retorno_60: 17,
      pct_retorno_90: 24,
    },
    { sku: "RARO", produto: "Produto raro", clientes: 4, ciclo_mediano: 20 },
  ],
  proximos: [
    {
      sku_origem: "CREA300",
      sku_seguinte: "CREA300",
      produto_seguinte: "Creatina 300g",
      ocorrencias: 2100,
      forca_pct: 61,
      pos: 1,
    },
    {
      sku_origem: "CREA300",
      sku_seguinte: "WHEY900",
      produto_seguinte: "Whey 900g",
      ocorrencias: 540,
      forca_pct: 16,
      pos: 2,
    },
  ],
  campanhas: [
    {
      campaign_id: 101,
      nome: "Semana da Creatina",
      data: "2026-09-10",
      enviado_em: "2026-09-10T10:00:00Z",
      contatos: 20000,
      entregues: 19700,
      aberturas: 9800,
      cliques: 690,
      bounces: 300,
      spam: 8,
      descadastros: 40,
    },
    {
      campaign_id: 102,
      nome: "Reposição Whey",
      data: "2026-09-20",
      enviado_em: "2026-09-20T10:00:00Z",
      contatos: 8000,
      entregues: 7500,
      aberturas: 3100,
      cliques: 150,
      bounces: 500,
      spam: 30,
      descadastros: 60,
    },
  ],
  vendasCampanha: [
    { campaign_id: 101, data: "2026-09-10", pedidos: 70, receita: 11200 },
    { campaign_id: 101, data: "2026-09-11", pedidos: 20, receita: 3100 },
    { campaign_id: 102, data: "2026-09-21", pedidos: 9, receita: 1900 },
  ],
  automacoes: [
    {
      data: "2026-09-12",
      fluxo: "Pós-compra creatina",
      contatos: 900,
      entregues: 880,
      aberturas: 500,
      cliques: 95,
      bounces: 10,
      descadastros: 2,
    },
    {
      data: "2026-09-13",
      fluxo: "Pós-compra creatina",
      contatos: 700,
      entregues: 690,
      aberturas: 400,
      cliques: 70,
      bounces: 6,
      descadastros: 1,
    },
    {
      data: "2026-09-13",
      fluxo: "Carrinho abandonado",
      contatos: 400,
      entregues: 380,
      aberturas: 210,
      cliques: 60,
      bounces: 15,
      descadastros: 4,
    },
  ],
  utm: [
    {
      data: "2026-09-10",
      utm_campaign: "semana-creatina",
      ligada_campanha: true,
      pedidos: 90,
      receita: 14300,
    },
    {
      data: "2026-09-14",
      utm_campaign: "pos-compra",
      ligada_campanha: false,
      pedidos: 30,
      receita: 4100,
    },
    { data: "2026-09-15", utm_campaign: "", ligada_campanha: false, pedidos: 4, receita: 500 },
  ],
  leadDia: [
    {
      data: "2026-09-05",
      origem: "Pop-up site",
      leads: 800,
      leads_compraram: 64,
      receita_leads: 9100,
    },
    {
      data: "2026-09-06",
      origem: "Pop-up site",
      leads: 400,
      leads_compraram: 26,
      receita_leads: 3600,
    },
    {
      data: "2026-09-06",
      origem: "Landing sorteio",
      leads: 1500,
      leads_compraram: 15,
      receita_leads: 1800,
    },
  ],
  leads: [
    {
      criado_em: "2026-09-05T10:00:00Z",
      estagio: "Lead",
      conversao: "popup-10off",
      utm_source: "site",
    },
    {
      criado_em: "2026-09-06T10:00:00Z",
      estagio: "Lead qualificado",
      conversao: "sorteio",
      utm_source: "instagram",
    },
    {
      criado_em: "2026-09-06T11:00:00Z",
      estagio: "Cliente",
      conversao: "popup-10off",
      utm_source: "site",
    },
  ],
  acoes: [
    {
      id: "a1",
      titulo: "Régua de reposição da creatina",
      canal: "email",
      status: "em andamento",
      responsavel: "CRM",
      prazo: "2026-09-20",
      prioridade: 1,
      impacto_estimado: 12000,
      esforco: "médio",
    },
    {
      id: "a2",
      titulo: "Cupom de 2ª compra no TikTok Shop",
      canal: "tiktok_shop",
      status: "concluida",
      responsavel: "Growth",
      prazo: "2026-09-10",
      prioridade: 2,
      impacto_estimado: 5000,
      esforco: "baixo",
    },
    {
      id: "a3",
      titulo: "Limpar base inativa do RD",
      canal: "email",
      status: "concluida",
      responsavel: "",
      prazo: "2026-09-05",
      prioridade: 3,
      impacto_estimado: null,
      esforco: "baixo",
    },
  ],
  resultados: [
    {
      acao_id: "a2",
      resultado: "positivo",
      metrica_antes: 100,
      metrica_depois: 130,
      observacao: "2ª compra subiu",
      registrado_em: "2026-09-25T10:00:00Z",
    },
  ],
  klaviyo: [
    {
      executado_em: "2026-09-30T06:00:00Z",
      modo: "resgate",
      ok: false,
      http_status: 401,
      perfis_no_segmento: null,
      erro: "token inválido",
    },
    {
      executado_em: "2026-09-29T06:00:00Z",
      modo: "resgate",
      ok: false,
      http_status: 401,
      perfis_no_segmento: null,
      erro: "token inválido",
    },
    {
      executado_em: "2026-09-28T06:00:00Z",
      modo: "resgate",
      ok: true,
      http_status: 202,
      perfis_no_segmento: 3120,
      erro: null,
    },
  ],
};

export function crmFixture() {
  const cal = calibracao(raw.acuracia);
  const regua = reguaReposicao(raw.ciclos, raw.proximos);
  const email = emailRD(raw.campanhas, raw.vendasCampanha, DE, ATE);
  const acoes = acoesGrowth(raw.acoes, raw.resultados, "2026-09-30");
  const klaviyo = saudeKlaviyo(raw.klaviyo, AGORA);
  return {
    fila: filaDeAcao(raw.perfis),
    calibracao: cal,
    geradoEm: "2026-09-30",
    regua,
    email,
    automacoes: automacoesRD(raw.automacoes, DE, ATE),
    utm: utmEmail(raw.utm, DE, ATE),
    leads: funilLeads(raw.leadDia, raw.leads, DE, ATE),
    acoes,
    klaviyo,
    alertas: alertasCRM({ klaviyo, email: email.total, calibracao: cal, acoes, regua }),
    erros: {} as Record<string, string>,
  };
}
