/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as CommerceRouteImport } from './routes/commerce'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DataHealthRouteImport } from './routes/data-health'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MediaRouteImport } from './routes/media'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesChaveRouteImport } from './routes/clientes.$chave'
import { Route as EmBreveModuloRouteImport } from './routes/em-breve.$modulo'
import { Route as PedidosIndexRouteImport } from './routes/pedidos.index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as ProdutosSkuRouteImport } from './routes/produtos.$sku'
import { Route as PedidosCanalIdRouteImport } from './routes/pedidos.$canal.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const CommerceRoute = CommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DataHealthRoute = DataHealthRouteImport.update({
  id: '/data-health',
  path: '/data-health',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesChaveRoute = ClientesChaveRouteImport.update({
  id: '/clientes/$chave',
  path: '/clientes/$chave',
  getParentRoute: () => rootRouteImport,
} as any)
const EmBreveModuloRoute = EmBreveModuloRouteImport.update({
  id: '/em-breve/$modulo',
  path: '/em-breve/$modulo',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSkuRoute = ProdutosSkuRouteImport.update({
  id: '/produtos/$sku',
  path: '/produtos/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosCanalIdRoute = PedidosCanalIdRouteImport.update({
  id: '/pedidos/$canal/$id',
  path: '/pedidos/$canal/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/commerce': typeof CommerceRoute
  '/crm': typeof CrmRoute
  '/data-health': typeof DataHealthRoute
  '/marketplace': typeof MarketplaceRoute
  '/media': typeof MediaRoute
  '/clientes/$chave': typeof ClientesChaveRoute
  '/em-breve/$modulo': typeof EmBreveModuloRoute
  '/produtos/$sku': typeof ProdutosSkuRoute
  '/clientes/': typeof ClientesIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/pedidos/$canal/$id': typeof PedidosCanalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/commerce': typeof CommerceRoute
  '/crm': typeof CrmRoute
  '/data-health': typeof DataHealthRoute
  '/marketplace': typeof MarketplaceRoute
  '/media': typeof MediaRoute
  '/clientes/$chave': typeof ClientesChaveRoute
  '/em-breve/$modulo': typeof EmBreveModuloRoute
  '/produtos/$sku': typeof ProdutosSkuRoute
  '/clientes': typeof ClientesIndexRoute
  '/pedidos': typeof PedidosIndexRoute
  '/produtos': typeof ProdutosIndexRoute
  '/pedidos/$canal/$id': typeof PedidosCanalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/commerce': typeof CommerceRoute
  '/crm': typeof CrmRoute
  '/data-health': typeof DataHealthRoute
  '/marketplace': typeof MarketplaceRoute
  '/media': typeof MediaRoute
  '/clientes/$chave': typeof ClientesChaveRoute
  '/em-breve/$modulo': typeof EmBreveModuloRoute
  '/produtos/$sku': typeof ProdutosSkuRoute
  '/clientes/': typeof ClientesIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/pedidos/$canal/$id': typeof PedidosCanalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliate'
    | '/commerce'
    | '/crm'
    | '/data-health'
    | '/marketplace'
    | '/media'
    | '/clientes/$chave'
    | '/em-breve/$modulo'
    | '/produtos/$sku'
    | '/clientes/'
    | '/pedidos/'
    | '/produtos/'
    | '/pedidos/$canal/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliate'
    | '/commerce'
    | '/crm'
    | '/data-health'
    | '/marketplace'
    | '/media'
    | '/clientes/$chave'
    | '/em-breve/$modulo'
    | '/produtos/$sku'
    | '/clientes'
    | '/pedidos'
    | '/produtos'
    | '/pedidos/$canal/$id'
  id:
    | '__root__'
    | '/'
    | '/affiliate'
    | '/commerce'
    | '/crm'
    | '/data-health'
    | '/marketplace'
    | '/media'
    | '/clientes/$chave'
    | '/em-breve/$modulo'
    | '/produtos/$sku'
    | '/clientes/'
    | '/pedidos/'
    | '/produtos/'
    | '/pedidos/$canal/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliateRoute: typeof AffiliateRoute
  CommerceRoute: typeof CommerceRoute
  CrmRoute: typeof CrmRoute
  DataHealthRoute: typeof DataHealthRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MediaRoute: typeof MediaRoute
  ClientesChaveRoute: typeof ClientesChaveRoute
  EmBreveModuloRoute: typeof EmBreveModuloRoute
  ProdutosSkuRoute: typeof ProdutosSkuRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
  PedidosCanalIdRoute: typeof PedidosCanalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commerce': {
      id: '/commerce'
      path: '/commerce'
      fullPath: '/commerce'
      preLoaderRoute: typeof CommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-health': {
      id: '/data-health'
      path: '/data-health'
      fullPath: '/data-health'
      preLoaderRoute: typeof DataHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$chave': {
      id: '/clientes/$chave'
      path: '/clientes/$chave'
      fullPath: '/clientes/$chave'
      preLoaderRoute: typeof ClientesChaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em-breve/$modulo': {
      id: '/em-breve/$modulo'
      path: '/em-breve/$modulo'
      fullPath: '/em-breve/$modulo'
      preLoaderRoute: typeof EmBreveModuloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$sku': {
      id: '/produtos/$sku'
      path: '/produtos/$sku'
      fullPath: '/produtos/$sku'
      preLoaderRoute: typeof ProdutosSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$canal/$id': {
      id: '/pedidos/$canal/$id'
      path: '/pedidos/$canal/$id'
      fullPath: '/pedidos/$canal/$id'
      preLoaderRoute: typeof PedidosCanalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliateRoute: AffiliateRoute,
  CommerceRoute: CommerceRoute,
  CrmRoute: CrmRoute,
  DataHealthRoute: DataHealthRoute,
  MarketplaceRoute: MarketplaceRoute,
  MediaRoute: MediaRoute,
  ClientesChaveRoute: ClientesChaveRoute,
  EmBreveModuloRoute: EmBreveModuloRoute,
  ProdutosSkuRoute: ProdutosSkuRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
  PedidosCanalIdRoute: PedidosCanalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
