/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as CommerceRouteImport } from './routes/commerce'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DataHealthRouteImport } from './routes/data-health'
import { Route as GlossarioRouteImport } from './routes/glossario'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MediaRouteImport } from './routes/media'
import { Route as AfiliadosHojeRouteImport } from './routes/afiliados.hoje'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesChaveRouteImport } from './routes/clientes.$chave'
import { Route as CrmAcaoRouteImport } from './routes/crm_.acao'
import { Route as EmBreveModuloRouteImport } from './routes/em-breve.$modulo'
import { Route as MarketplaceAmazonRouteImport } from './routes/marketplace_.amazon'
import { Route as MarketplaceMercadoLivreRouteImport } from './routes/marketplace_.mercado-livre'
import { Route as MarketplaceShopeeRouteImport } from './routes/marketplace_.shopee'
import { Route as MarketplaceTiktokRouteImport } from './routes/marketplace_.tiktok'
import { Route as MediaGoogleRouteImport } from './routes/media_.google'
import { Route as MediaMetaRouteImport } from './routes/media_.meta'
import { Route as PedidosIndexRouteImport } from './routes/pedidos.index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as ProdutosSkuRouteImport } from './routes/produtos.$sku'
import { Route as MediaMetaCriativosRouteImport } from './routes/media_.meta_.criativos'
import { Route as PedidosCanalIdRouteImport } from './routes/pedidos.$canal.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const CommerceRoute = CommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DataHealthRoute = DataHealthRouteImport.update({
  id: '/data-health',
  path: '/data-health',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioRoute = GlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadosHojeRoute = AfiliadosHojeRouteImport.update({
  id: '/afiliados/hoje',
  path: '/afiliados/hoje',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesChaveRoute = ClientesChaveRouteImport.update({
  id: '/clientes/$chave',
  path: '/clientes/$chave',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmAcaoRoute = CrmAcaoRouteImport.update({
  id: '/crm_/acao',
  path: '/crm/acao',
  getParentRoute: () => rootRouteImport,
} as any)
const EmBreveModuloRoute = EmBreveModuloRouteImport.update({
  id: '/em-breve/$modulo',
  path: '/em-breve/$modulo',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceAmazonRoute = MarketplaceAmazonRouteImport.update({
  id: '/marketplace_/amazon',
  path: '/marketplace/amazon',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceMercadoLivreRoute = MarketplaceMercadoLivreRouteImport.update({
  id: '/marketplace_/mercado-livre',
  path: '/marketplace/mercado-livre',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceShopeeRoute = MarketplaceShopeeRouteImport.update({
  id: '/marketplace_/shopee',
  path: '/marketplace/shopee',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceTiktokRoute = MarketplaceTiktokRouteImport.update({
  id: '/marketplace_/tiktok',
  path: '/marketplace/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaGoogleRoute = MediaGoogleRouteImport.update({
  id: '/media_/google',
  path: '/media/google',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaMetaRoute = MediaMetaRouteImport.update({
  id: '/media_/meta',
  path: '/media/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSkuRoute = ProdutosSkuRouteImport.update({
  id: '/produtos/$sku',
  path: '/produtos/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaMetaCriativosRoute = MediaMetaCriativosRouteImport.update({
  id: '/media_/meta_/criativos',
  path: '/media/meta/criativos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosCanalIdRoute = PedidosCanalIdRouteImport.update({
  id: '/pedidos/$canal/$id',
  path: '/pedidos/$canal/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/commerce': typeof CommerceRoute
  '/crm': typeof CrmRoute
  '/data-health': typeof DataHealthRoute
  '/glossario': typeof GlossarioRoute
  '/marketplace': typeof MarketplaceRoute
  '/media': typeof MediaRoute
  '/afiliados/hoje': typeof AfiliadosHojeRoute
  '/clientes/$chave': typeof ClientesChaveRoute
  '/crm/acao': typeof CrmAcaoRoute
  '/em-breve/$modulo': typeof EmBreveModuloRoute
  '/marketplace/amazon': typeof MarketplaceAmazonRoute
  '/marketplace/mercado-livre': typeof MarketplaceMercadoLivreRoute
  '/marketplace/shopee': typeof MarketplaceShopeeRoute
  '/marketplace/tiktok': typeof MarketplaceTiktokRoute
  '/media/google': typeof MediaGoogleRoute
  '/media/meta': typeof MediaMetaRoute
  '/produtos/$sku': typeof ProdutosSkuRoute
  '/clientes/': typeof ClientesIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/media/meta/criativos': typeof MediaMetaCriativosRoute
  '/pedidos/$canal/$id': typeof PedidosCanalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/commerce': typeof CommerceRoute
  '/crm': typeof CrmRoute
  '/data-health': typeof DataHealthRoute
  '/glossario': typeof GlossarioRoute
  '/marketplace': typeof MarketplaceRoute
  '/media': typeof MediaRoute
  '/afiliados/hoje': typeof AfiliadosHojeRoute
  '/clientes/$chave': typeof ClientesChaveRoute
  '/crm/acao': typeof CrmAcaoRoute
  '/em-breve/$modulo': typeof EmBreveModuloRoute
  '/marketplace/amazon': typeof MarketplaceAmazonRoute
  '/marketplace/mercado-livre': typeof MarketplaceMercadoLivreRoute
  '/marketplace/shopee': typeof MarketplaceShopeeRoute
  '/marketplace/tiktok': typeof MarketplaceTiktokRoute
  '/media/google': typeof MediaGoogleRoute
  '/media/meta': typeof MediaMetaRoute
  '/produtos/$sku': typeof ProdutosSkuRoute
  '/clientes': typeof ClientesIndexRoute
  '/pedidos': typeof PedidosIndexRoute
  '/produtos': typeof ProdutosIndexRoute
  '/media/meta/criativos': typeof MediaMetaCriativosRoute
  '/pedidos/$canal/$id': typeof PedidosCanalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/commerce': typeof CommerceRoute
  '/crm': typeof CrmRoute
  '/data-health': typeof DataHealthRoute
  '/glossario': typeof GlossarioRoute
  '/marketplace': typeof MarketplaceRoute
  '/media': typeof MediaRoute
  '/afiliados/hoje': typeof AfiliadosHojeRoute
  '/clientes/$chave': typeof ClientesChaveRoute
  '/crm_/acao': typeof CrmAcaoRoute
  '/em-breve/$modulo': typeof EmBreveModuloRoute
  '/marketplace_/amazon': typeof MarketplaceAmazonRoute
  '/marketplace_/mercado-livre': typeof MarketplaceMercadoLivreRoute
  '/marketplace_/shopee': typeof MarketplaceShopeeRoute
  '/marketplace_/tiktok': typeof MarketplaceTiktokRoute
  '/media_/google': typeof MediaGoogleRoute
  '/media_/meta': typeof MediaMetaRoute
  '/produtos/$sku': typeof ProdutosSkuRoute
  '/clientes/': typeof ClientesIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/media_/meta_/criativos': typeof MediaMetaCriativosRoute
  '/pedidos/$canal/$id': typeof PedidosCanalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliate'
    | '/commerce'
    | '/crm'
    | '/data-health'
    | '/glossario'
    | '/marketplace'
    | '/media'
    | '/afiliados/hoje'
    | '/clientes/$chave'
    | '/crm/acao'
    | '/em-breve/$modulo'
    | '/marketplace/amazon'
    | '/marketplace/mercado-livre'
    | '/marketplace/shopee'
    | '/marketplace/tiktok'
    | '/media/google'
    | '/media/meta'
    | '/produtos/$sku'
    | '/clientes/'
    | '/pedidos/'
    | '/produtos/'
    | '/media/meta/criativos'
    | '/pedidos/$canal/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliate'
    | '/commerce'
    | '/crm'
    | '/data-health'
    | '/glossario'
    | '/marketplace'
    | '/media'
    | '/afiliados/hoje'
    | '/clientes/$chave'
    | '/crm/acao'
    | '/em-breve/$modulo'
    | '/marketplace/amazon'
    | '/marketplace/mercado-livre'
    | '/marketplace/shopee'
    | '/marketplace/tiktok'
    | '/media/google'
    | '/media/meta'
    | '/produtos/$sku'
    | '/clientes'
    | '/pedidos'
    | '/produtos'
    | '/media/meta/criativos'
    | '/pedidos/$canal/$id'
  id:
    | '__root__'
    | '/'
    | '/affiliate'
    | '/commerce'
    | '/crm'
    | '/data-health'
    | '/glossario'
    | '/marketplace'
    | '/media'
    | '/afiliados/hoje'
    | '/clientes/$chave'
    | '/crm_/acao'
    | '/em-breve/$modulo'
    | '/marketplace_/amazon'
    | '/marketplace_/mercado-livre'
    | '/marketplace_/shopee'
    | '/marketplace_/tiktok'
    | '/media_/google'
    | '/media_/meta'
    | '/produtos/$sku'
    | '/clientes/'
    | '/pedidos/'
    | '/produtos/'
    | '/media_/meta_/criativos'
    | '/pedidos/$canal/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliateRoute: typeof AffiliateRoute
  CommerceRoute: typeof CommerceRoute
  CrmRoute: typeof CrmRoute
  DataHealthRoute: typeof DataHealthRoute
  GlossarioRoute: typeof GlossarioRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MediaRoute: typeof MediaRoute
  AfiliadosHojeRoute: typeof AfiliadosHojeRoute
  ClientesChaveRoute: typeof ClientesChaveRoute
  CrmAcaoRoute: typeof CrmAcaoRoute
  EmBreveModuloRoute: typeof EmBreveModuloRoute
  MarketplaceAmazonRoute: typeof MarketplaceAmazonRoute
  MarketplaceMercadoLivreRoute: typeof MarketplaceMercadoLivreRoute
  MarketplaceShopeeRoute: typeof MarketplaceShopeeRoute
  MarketplaceTiktokRoute: typeof MarketplaceTiktokRoute
  MediaGoogleRoute: typeof MediaGoogleRoute
  MediaMetaRoute: typeof MediaMetaRoute
  ProdutosSkuRoute: typeof ProdutosSkuRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
  MediaMetaCriativosRoute: typeof MediaMetaCriativosRoute
  PedidosCanalIdRoute: typeof PedidosCanalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commerce': {
      id: '/commerce'
      path: '/commerce'
      fullPath: '/commerce'
      preLoaderRoute: typeof CommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-health': {
      id: '/data-health'
      path: '/data-health'
      fullPath: '/data-health'
      preLoaderRoute: typeof DataHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario': {
      id: '/glossario'
      path: '/glossario'
      fullPath: '/glossario'
      preLoaderRoute: typeof GlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliados/hoje': {
      id: '/afiliados/hoje'
      path: '/afiliados/hoje'
      fullPath: '/afiliados/hoje'
      preLoaderRoute: typeof AfiliadosHojeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$chave': {
      id: '/clientes/$chave'
      path: '/clientes/$chave'
      fullPath: '/clientes/$chave'
      preLoaderRoute: typeof ClientesChaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm_/acao': {
      id: '/crm_/acao'
      path: '/crm/acao'
      fullPath: '/crm/acao'
      preLoaderRoute: typeof CrmAcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em-breve/$modulo': {
      id: '/em-breve/$modulo'
      path: '/em-breve/$modulo'
      fullPath: '/em-breve/$modulo'
      preLoaderRoute: typeof EmBreveModuloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace_/amazon': {
      id: '/marketplace_/amazon'
      path: '/marketplace/amazon'
      fullPath: '/marketplace/amazon'
      preLoaderRoute: typeof MarketplaceAmazonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace_/mercado-livre': {
      id: '/marketplace_/mercado-livre'
      path: '/marketplace/mercado-livre'
      fullPath: '/marketplace/mercado-livre'
      preLoaderRoute: typeof MarketplaceMercadoLivreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace_/shopee': {
      id: '/marketplace_/shopee'
      path: '/marketplace/shopee'
      fullPath: '/marketplace/shopee'
      preLoaderRoute: typeof MarketplaceShopeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace_/tiktok': {
      id: '/marketplace_/tiktok'
      path: '/marketplace/tiktok'
      fullPath: '/marketplace/tiktok'
      preLoaderRoute: typeof MarketplaceTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media_/google': {
      id: '/media_/google'
      path: '/media/google'
      fullPath: '/media/google'
      preLoaderRoute: typeof MediaGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media_/meta': {
      id: '/media_/meta'
      path: '/media/meta'
      fullPath: '/media/meta'
      preLoaderRoute: typeof MediaMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$sku': {
      id: '/produtos/$sku'
      path: '/produtos/$sku'
      fullPath: '/produtos/$sku'
      preLoaderRoute: typeof ProdutosSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media_/meta_/criativos': {
      id: '/media_/meta_/criativos'
      path: '/media/meta/criativos'
      fullPath: '/media/meta/criativos'
      preLoaderRoute: typeof MediaMetaCriativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$canal/$id': {
      id: '/pedidos/$canal/$id'
      path: '/pedidos/$canal/$id'
      fullPath: '/pedidos/$canal/$id'
      preLoaderRoute: typeof PedidosCanalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliateRoute: AffiliateRoute,
  CommerceRoute: CommerceRoute,
  CrmRoute: CrmRoute,
  DataHealthRoute: DataHealthRoute,
  GlossarioRoute: GlossarioRoute,
  MarketplaceRoute: MarketplaceRoute,
  MediaRoute: MediaRoute,
  AfiliadosHojeRoute: AfiliadosHojeRoute,
  ClientesChaveRoute: ClientesChaveRoute,
  CrmAcaoRoute: CrmAcaoRoute,
  EmBreveModuloRoute: EmBreveModuloRoute,
  MarketplaceAmazonRoute: MarketplaceAmazonRoute,
  MarketplaceMercadoLivreRoute: MarketplaceMercadoLivreRoute,
  MarketplaceShopeeRoute: MarketplaceShopeeRoute,
  MarketplaceTiktokRoute: MarketplaceTiktokRoute,
  MediaGoogleRoute: MediaGoogleRoute,
  MediaMetaRoute: MediaMetaRoute,
  ProdutosSkuRoute: ProdutosSkuRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
  MediaMetaCriativosRoute: MediaMetaCriativosRoute,
  PedidosCanalIdRoute: PedidosCanalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
